// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgaung5tXLmk0cXc80FL0HRLGLbObbalo',
    appId: '1:266861350362:web:484e576bb7415cadc504e3',
    messagingSenderId: '266861350362',
    projectId: 'emerg-91167',
    authDomain: 'emerg-91167.firebaseapp.com',
    databaseURL: 'https://emerg-91167-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'emerg-91167.firebasestorage.app',
    measurementId: 'G-V01M827VNC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8v5t_A6CZNjpCPumdY8aUJwfeoF6K0JU',
    appId: '1:266861350362:android:2af2ddb0471de9c1c504e3',
    messagingSenderId: '266861350362',
    projectId: 'emerg-91167',
    databaseURL: 'https://emerg-91167-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'emerg-91167.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLCtNh6UzBKkwYqPUCG2Ul9O4aQ6eq_KM',
    appId: '1:266861350362:ios:2f74f02072166d07c504e3',
    messagingSenderId: '266861350362',
    projectId: 'emerg-91167',
    databaseURL: 'https://emerg-91167-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'emerg-91167.firebasestorage.app',
    iosBundleId: 'com.example.capstoneApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLCtNh6UzBKkwYqPUCG2Ul9O4aQ6eq_KM',
    appId: '1:266861350362:ios:2f74f02072166d07c504e3',
    messagingSenderId: '266861350362',
    projectId: 'emerg-91167',
    databaseURL: 'https://emerg-91167-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'emerg-91167.firebasestorage.app',
    iosBundleId: 'com.example.capstoneApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgaung5tXLmk0cXc80FL0HRLGLbObbalo',
    appId: '1:266861350362:web:858a8c5e79be8420c504e3',
    messagingSenderId: '266861350362',
    projectId: 'emerg-91167',
    authDomain: 'emerg-91167.firebaseapp.com',
    databaseURL: 'https://emerg-91167-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'emerg-91167.firebasestorage.app',
    measurementId: 'G-HEF3WXJCHR',
  );
}
